language: generic
sudo: required
services:
  - docker


  before_install:
    - docker build -t meffowe24/react-test -f ./client/Dockerfile.dev ./client

  script:
    - docker run -e CI=true meffowe24/react-test npm test

  after_success:
    - docker build -t meffowe24/multi-client ./client
    - docker build -t meffowe24/multi-nginx ./nginx
    - docker build -t meffowe24/multi-server ./server
    - docker build -t meffowe24/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$Docker_ID" --password-stdin 
    # Take those images and push them to docker hub
    - docker push meffowe24/multi-client
    - docker push meffowe24/multi-nginx
    - docker push meffowe24/multi-server
    - docker push meffowe24/multi-worker



  
